### ISSUE TITLE
「【依頼】最終課題挙動確認」

### ISSUE THREAD

**Issue by white-papers** [white-papers/fleamarket_sample_77a#79]
■ URL
IPアドレス：http://13.113.13.211/
Github（最終課題のリポジトリ）：https://github.com/white-papers/fleamarket_sample_77a

■ Basic認証
ID：team77a
Pass：77a77a

■ テスト用アカウント
◯ 購入者用
メールアドレス：buyer_user@gmail.com
パスワード：buyer_user

◯ 購入用カード情報
番号：4242424242424242
期限：12 / 22
セキュリティカード：123

◯ 出品者用
メールアドレス：seller_user@gmail.com
パスワード：seller_user

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**[修正依頼箇所]**
**①商品情報の[ サイズ及び配送方法 ]は必須でない為、任意にしましょう。**
**（物（文具等）によりサイズがない物もある為。）**

**②商品情報を編集する際、登録した物から編集できるようにしましょう。**
　**現状は編集する際、[商品の情報〜発送日の目安]までの項目が初期化されてしまいます。**

修正し次第、以下の最終課題完了報告フォームを再度ご提出して下さい！
https://docs.google.com/forms/d/e/1FAIpQLSfwbel-Pb-WLCubi00-8oV_WOhp0XamSMsd9h8UHROi9LSRcA/viewform

**Comment by white-papers** [comment]
ご確認ありがとうございます！
修正依頼箇所について、承知いたしました。

①商品情報のサイズ及び配送方法を任意にできるよう修正いたしました。
②登録した物から編集できるようにするため、項目が初期化されないように修正いたしました。

ご確認のほどよろしくお願いいたします。

**Comment by mutorisa** [comment]
修正後、再度ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかチーム内で再度確認しましょう。**
